### ISSUE TITLE
There is no version 4.0.6 on Maven

### ISSUE THREAD

**Issue by daniloakamine** [NeverBounce/NeverBounceApi-Java#27]
The example suggests that I use version 4.0.6 on Maven.
However, I can't find this version on repositories like these:

https://search.maven.org/search?q=g:com.neverbounce
https://mvnrepository.com/artifact/com.neverbounce/neverbounce-api-java

The last version published there is 4.0.5.
Can I follow the examples if I use this version? They will work?

Thanks.

**Comment by daniloakamine** [comment]
Well, I tested version 4.0.5 and the examples are working properly.
By the way, this SDK is very nice, simple and intuitive.
Congrats guys.

**Comment by david-borrowman** [comment]
Thank you kindly for bringing this to our attention. We made a mistake with the versioning. 4.0.5 was the latest version. Our automated deploy process needed a bit of attention. I have sorted all this out so it should not be a problem in the future. We are now at version 4.0.8. There were no changes outside of some fumbling with the build process. Please excuse the confusion.

I am very glad to hear you enjoy working with the SDK. Please let us know if you have any questions. Happy coding!

**Comment by daniloakamine** [comment]
Awesome! Thanks.
