### ISSUE TITLE
"profanity" flag value not available in Flag.java. Causes exception while parsing response

### ISSUE THREAD

**Issue by qutubdahodwala** [NeverBounce/NeverBounceApi-Java#29]
Response received through API contains the following json for 'flags' for some email ids
**flags: ["free_email_host", "profanity", "has_dns", "has_dns_mx", "smtp_connectable"]**

**Comment by panditankur** [comment]
An update has been pushed which would fix the issue. Please upgrade your wrapper to use v4.0.9
